#include "stdafx.h"
#include "processor.h"

BEGIN_NAMESPACE_LOCHSEMU()

Processor::InstHandler Processor::InstTableOneByte[] = 
{
    /*0x00*/ &Processor::Add_00,
    /*0x01*/ &Processor::Add_01,
    /*0x02*/ &Processor::Add_02,
    /*0x03*/ &Processor::Add_03,
    /*0x04*/ &Processor::Add_04,
    /*0x05*/ &Processor::Add_05,
    /*0x06*/ &Processor::InstNotAvailable,
    /*0x07*/ &Processor::InstNotAvailable,
    /*0x08*/ &Processor::Or_08,
    /*0x09*/ &Processor::Or_09,
    /*0x0a*/ &Processor::Or_0A,
    /*0x0b*/ &Processor::Or_0B,
    /*0x0c*/ &Processor::Or_0C,
    /*0x0d*/ &Processor::Or_0D,
    /*0x0e*/ &Processor::InstNotAvailable,
    /*0x0f*/ &Processor::InstNotAvailable,
    /*0x10*/ &Processor::InstNotAvailable,
    /*0x11*/ &Processor::InstNotAvailable,
    /*0x12*/ &Processor::Adc_12,
    /*0x13*/ &Processor::Adc_13,
    /*0x14*/ &Processor::InstNotAvailable,
    /*0x15*/ &Processor::InstNotAvailable,
    /*0x16*/ &Processor::InstNotAvailable,
    /*0x17*/ &Processor::InstNotAvailable,
    /*0x18*/ &Processor::InstNotAvailable,
    /*0x19*/ &Processor::Sbb_19,
    /*0x1a*/ &Processor::Sbb_1A,
    /*0x1b*/ &Processor::Sbb_1B,
    /*0x1c*/ &Processor::InstNotAvailable,
    /*0x1d*/ &Processor::InstNotAvailable,
    /*0x1e*/ &Processor::InstNotAvailable,
    /*0x1f*/ &Processor::InstNotAvailable,
    /*0x20*/ &Processor::And_20,
    /*0x21*/ &Processor::And_21,
    /*0x22*/ &Processor::And_22,
    /*0x23*/ &Processor::And_23,
    /*0x24*/ &Processor::And_24,
    /*0x25*/ &Processor::And_25,
    /*0x26*/ &Processor::InstNotAvailable,
    /*0x27*/ &Processor::InstNotAvailable,
    /*0x28*/ &Processor::Sub_28,
    /*0x29*/ &Processor::Sub_29,
    /*0x2a*/ &Processor::Sub_2A,
    /*0x2b*/ &Processor::Sub_2B,
    /*0x2c*/ &Processor::Sub_2C,
    /*0x2d*/ &Processor::Sub_2D,
    /*0x2e*/ &Processor::InstNotAvailable,
    /*0x2f*/ &Processor::InstNotAvailable,
    /*0x30*/ &Processor::Xor_30,
    /*0x31*/ &Processor::Xor_31,
    /*0x32*/ &Processor::Xor_32,
    /*0x33*/ &Processor::Xor_33,
    /*0x34*/ &Processor::Xor_34,
    /*0x35*/ &Processor::Xor_35,
    /*0x36*/ &Processor::InstNotAvailable,
    /*0x37*/ &Processor::InstNotAvailable,
    /*0x38*/ &Processor::Cmp_38,
    /*0x39*/ &Processor::Cmp_39,
    /*0x3a*/ &Processor::Cmp_3A,
    /*0x3b*/ &Processor::Cmp_3B,
    /*0x3c*/ &Processor::Cmp_3C,
    /*0x3d*/ &Processor::Cmp_3D,
    /*0x3e*/ &Processor::InstNotAvailable,
    /*0x3f*/ &Processor::InstNotAvailable,
    /*0x40*/ &Processor::Inc_40X,
    /*0x41*/ &Processor::Inc_40X,
    /*0x42*/ &Processor::Inc_40X,
    /*0x43*/ &Processor::Inc_40X,
    /*0x44*/ &Processor::Inc_40X,
    /*0x45*/ &Processor::Inc_40X,
    /*0x46*/ &Processor::Inc_40X,
    /*0x47*/ &Processor::Inc_40X,
    /*0x48*/ &Processor::Dec_48X,
    /*0x49*/ &Processor::Dec_48X,
    /*0x4a*/ &Processor::Dec_48X,
    /*0x4b*/ &Processor::Dec_48X,
    /*0x4c*/ &Processor::Dec_48X,
    /*0x4d*/ &Processor::Dec_48X,
    /*0x4e*/ &Processor::Dec_48X,
    /*0x4f*/ &Processor::Dec_48X,
    /*0x50*/ &Processor::Push_50X,
    /*0x51*/ &Processor::Push_50X,
    /*0x52*/ &Processor::Push_50X,
    /*0x53*/ &Processor::Push_50X,
    /*0x54*/ &Processor::Push_50X,
    /*0x55*/ &Processor::Push_50X,
    /*0x56*/ &Processor::Push_50X,
    /*0x57*/ &Processor::Push_50X,
    /*0x58*/ &Processor::Pop_58X,
    /*0x59*/ &Processor::Pop_58X,
    /*0x5a*/ &Processor::Pop_58X,
    /*0x5b*/ &Processor::Pop_58X,
    /*0x5c*/ &Processor::Pop_58X,
    /*0x5d*/ &Processor::Pop_58X,
    /*0x5e*/ &Processor::Pop_58X,
    /*0x5f*/ &Processor::Pop_58X,
    /*0x60*/ &Processor::Pushad_60,
    /*0x61*/ &Processor::Popad_61,
    /*0x62*/ &Processor::Bound_62,
    /*0x63*/ &Processor::InstNotAvailable,
    /*0x64*/ &Processor::InstNotAvailable,
    /*0x65*/ &Processor::InstNotAvailable,
    /*0x66*/ &Processor::InstNotAvailable,
    /*0x67*/ &Processor::InstNotAvailable,
    /*0x68*/ &Processor::Push_68,
    /*0x69*/ &Processor::Imul_69,
    /*0x6a*/ &Processor::Push_6A,
    /*0x6b*/ &Processor::Imul_6B,
    /*0x6c*/ &Processor::InstNotAvailable,
    /*0x6d*/ &Processor::InstNotAvailable,
    /*0x6e*/ &Processor::InstNotAvailable,
    /*0x6f*/ &Processor::InstNotAvailable,
    /*0x70*/ &Processor::Jo_70,
    /*0x71*/ &Processor::Jno_71,
    /*0x72*/ &Processor::Jb_72,
    /*0x73*/ &Processor::Jnb_73,
    /*0x74*/ &Processor::Je_74,
    /*0x75*/ &Processor::Jne_75,
    /*0x76*/ &Processor::Jbe_76,
    /*0x77*/ &Processor::Ja_77,
    /*0x78*/ &Processor::Js_78,
    /*0x79*/ &Processor::Jns_79,
    /*0x7a*/ &Processor::Jp_7A,
    /*0x7b*/ &Processor::Jnp_7B,
    /*0x7c*/ &Processor::Jl_7C,
    /*0x7d*/ &Processor::Jge_7D,
    /*0x7e*/ &Processor::Jle_7E,
    /*0x7f*/ &Processor::Jg_7F,
    /*0x80*/ &Processor::Ext_80,
    /*0x81*/ &Processor::Ext_81,
    /*0x82*/ &Processor::InstNotAvailable,
    /*0x83*/ &Processor::Ext_83,
    /*0x84*/ &Processor::Test_84,
    /*0x85*/ &Processor::Test_85,
    /*0x86*/ &Processor::InstNotAvailable,
    /*0x87*/ &Processor::Xchg_87,
    /*0x88*/ &Processor::Mov_88,
    /*0x89*/ &Processor::Mov_89,
    /*0x8a*/ &Processor::Mov_8A,
    /*0x8b*/ &Processor::Mov_8B,
    /*0x8c*/ &Processor::Mov_8C,
    /*0x8d*/ &Processor::Lea_8D,
    /*0x8e*/ &Processor::InstNotAvailable,
    /*0x8f*/ &Processor::Ext_8F,
    /*0x90*/ &Processor::Nop_90,
    /*0x91*/ &Processor::Xchg_90X,
    /*0x92*/ &Processor::Xchg_90X,
    /*0x93*/ &Processor::Xchg_90X,
    /*0x94*/ &Processor::Xchg_90X,
    /*0x95*/ &Processor::Xchg_90X,
    /*0x96*/ &Processor::Xchg_90X,
    /*0x97*/ &Processor::Xchg_90X,
    /*0x98*/ &Processor::Cbw_98,
    /*0x99*/ &Processor::Cdq_99,
    /*0x9a*/ &Processor::InstNotAvailable,
    /*0x9b*/ &Processor::Fpu_Wait_9B,
    /*0x9c*/ &Processor::Pushf_9C,
    /*0x9d*/ &Processor::Popf_9D,
    /*0x9e*/ &Processor::Sahf_9E,
    /*0x9f*/ &Processor::InstNotAvailable,
    /*0xa0*/ &Processor::Mov_A0,
    /*0xa1*/ &Processor::Mov_A1,
    /*0xa2*/ &Processor::Mov_A2,
    /*0xa3*/ &Processor::Mov_A3,
    /*0xa4*/ &Processor::Movsb_A4,
    /*0xa5*/ &Processor::Movs_A5,
	/*0xa6*/ &Processor::Cmpsb_A6,
    /*0xa7*/ &Processor::Cmpsd_A7,
    /*0xa8*/ &Processor::Test_A8,
    /*0xa9*/ &Processor::Test_A9,
    /*0xaa*/ &Processor::Stos_AA,
    /*0xab*/ &Processor::Stos_AB,
    /*0xac*/ &Processor::Lodsb_AC,
    /*0xad*/ &Processor::Lodsd_AD,
    /*0xae*/ &Processor::Scasb_AE,
    /*0xaf*/ &Processor::InstNotAvailable,
    /*0xb0*/ &Processor::Mov_B0X,
    /*0xb1*/ &Processor::Mov_B0X,
    /*0xb2*/ &Processor::Mov_B0X,
    /*0xb3*/ &Processor::Mov_B0X,
    /*0xb4*/ &Processor::Mov_B0X,
    /*0xb5*/ &Processor::Mov_B0X,
    /*0xb6*/ &Processor::Mov_B0X,
    /*0xb7*/ &Processor::Mov_B0X,
    /*0xb8*/ &Processor::Mov_B8X,
    /*0xb9*/ &Processor::Mov_B8X,
    /*0xba*/ &Processor::Mov_B8X,
    /*0xbb*/ &Processor::Mov_B8X,
    /*0xbc*/ &Processor::Mov_B8X,
    /*0xbd*/ &Processor::Mov_B8X,
    /*0xbe*/ &Processor::Mov_B8X,
    /*0xbf*/ &Processor::Mov_B8X,
    /*0xc0*/ &Processor::Ext_C0,
    /*0xc1*/ &Processor::Ext_C1,
    /*0xc2*/ &Processor::Retn_C2,
    /*0xc3*/ &Processor::Ret_C3,
    /*0xc4*/ &Processor::InstNotAvailable,
    /*0xc5*/ &Processor::InstNotAvailable,
    /*0xc6*/ &Processor::Ext_C6,
    /*0xc7*/ &Processor::Ext_C7,
    /*0xc8*/ &Processor::Enter_C8,
    /*0xc9*/ &Processor::Leave_C9,
    /*0xca*/ &Processor::InstNotAvailable,
    /*0xcb*/ &Processor::InstNotAvailable,
    /*0xcc*/ &Processor::Int3_CC,
    /*0xcd*/ &Processor::InstNotAvailable,
    /*0xce*/ &Processor::InstNotAvailable,
    /*0xcf*/ &Processor::InstNotAvailable,
    /*0xd0*/ &Processor::Ext_D0,
    /*0xd1*/ &Processor::Ext_D1,
    /*0xd2*/ &Processor::Ext_D2,
    /*0xd3*/ &Processor::Ext_D3,
    /*0xd4*/ &Processor::InstNotAvailable,
    /*0xd5*/ &Processor::InstNotAvailable,
    /*0xd6*/ &Processor::InstNotAvailable,
    /*0xd7*/ &Processor::Xlat_D7,
    /*0xd8*/ &Processor::Fpu_Ext,
    /*0xd9*/ &Processor::Fpu_Ext,
    /*0xda*/ &Processor::Fpu_Ext,
    /*0xdb*/ &Processor::Fpu_Ext,
    /*0xdc*/ &Processor::Fpu_Ext,
    /*0xdd*/ &Processor::Fpu_Ext,
    /*0xde*/ &Processor::Fpu_Ext,
    /*0xdf*/ &Processor::Fpu_Ext,
    /*0xe0*/ &Processor::InstNotAvailable,
    /*0xe1*/ &Processor::InstNotAvailable,
    /*0xe2*/ &Processor::Loop_E2,
    /*0xe3*/ &Processor::Jecxz_E3,
    /*0xe4*/ &Processor::InstNotAvailable,
    /*0xe5*/ &Processor::InstNotAvailable,
    /*0xe6*/ &Processor::InstNotAvailable,
    /*0xe7*/ &Processor::InstNotAvailable,
    /*0xe8*/ &Processor::Call_E8,
    /*0xe9*/ &Processor::Jmp_E9,
    /*0xea*/ &Processor::InstNotAvailable,
    /*0xeb*/ &Processor::Jmp_EB,
    /*0xec*/ &Processor::InstNotAvailable,
    /*0xed*/ &Processor::InstNotAvailable,
    /*0xee*/ &Processor::InstNotAvailable,
    /*0xef*/ &Processor::InstNotAvailable,
    /*0xf0*/ &Processor::InstNotAvailable,
    /*0xf1*/ &Processor::InstNotAvailable,
    /*0xf2*/ &Processor::InstNotAvailable,
    /*0xf3*/ &Processor::InstNotAvailable,
    /*0xf4*/ &Processor::InstNotAvailable,
    /*0xf5*/ &Processor::Cmc_F5,
    /*0xf6*/ &Processor::Ext_F6,
    /*0xf7*/ &Processor::Ext_F7,
    /*0xf8*/ &Processor::Clc_F8,
    /*0xf9*/ &Processor::Stc_F9,
    /*0xfa*/ &Processor::Cli_FA,
    /*0xfb*/ &Processor::Sti_FB,
    /*0xfc*/ &Processor::Cld_FC,
    /*0xfd*/ &Processor::Std_FD,
    /*0xfe*/ &Processor::Ext_FE,
    /*0xff*/ &Processor::Ext_FF,

};

Processor::InstHandler Processor::InstTableTwoBytes[] = 
{
    /*0f 00*/ &Processor::InstNotAvailable,
    /*0f 01*/ &Processor::Xgetbv_0F01,
    /*0f 02*/ &Processor::InstNotAvailable,
    /*0f 03*/ &Processor::InstNotAvailable,
    /*0f 04*/ &Processor::InstNotAvailable,
    /*0f 05*/ &Processor::InstNotAvailable,
    /*0f 06*/ &Processor::InstNotAvailable,
    /*0f 07*/ &Processor::InstNotAvailable,
    /*0f 08*/ &Processor::InstNotAvailable,
    /*0f 09*/ &Processor::InstNotAvailable,
    /*0f 0a*/ &Processor::InstNotAvailable,
    /*0f 0b*/ &Processor::InstNotAvailable,
    /*0f 0c*/ &Processor::InstNotAvailable,
    /*0f 0d*/ &Processor::InstNotAvailable,
    /*0f 0e*/ &Processor::InstNotAvailable,
    /*0f 0f*/ &Processor::InstNotAvailable,
    /*0f 10*/ &Processor::InstNotAvailable,
    /*0f 11*/ &Processor::InstNotAvailable,
    /*0f 12*/ &Processor::InstNotAvailable,
    /*0f 13*/ &Processor::InstNotAvailable,
    /*0f 14*/ &Processor::InstNotAvailable,
    /*0f 15*/ &Processor::InstNotAvailable,
    /*0f 16*/ &Processor::InstNotAvailable,
    /*0f 17*/ &Processor::InstNotAvailable,
    /*0f 18*/ &Processor::InstNotAvailable,
    /*0f 19*/ &Processor::InstNotAvailable,
    /*0f 1a*/ &Processor::InstNotAvailable,
    /*0f 1b*/ &Processor::InstNotAvailable,
    /*0f 1c*/ &Processor::InstNotAvailable,
    /*0f 1d*/ &Processor::InstNotAvailable,
    /*0f 1e*/ &Processor::InstNotAvailable,
    /*0f 1f*/ &Processor::Ext_0F1F,
    /*0f 20*/ &Processor::InstNotAvailable,
    /*0f 21*/ &Processor::InstNotAvailable,
    /*0f 22*/ &Processor::InstNotAvailable,
    /*0f 23*/ &Processor::InstNotAvailable,
    /*0f 24*/ &Processor::InstNotAvailable,
    /*0f 25*/ &Processor::InstNotAvailable,
    /*0f 26*/ &Processor::InstNotAvailable,
    /*0f 27*/ &Processor::InstNotAvailable,
    /*0f 28*/ &Processor::Movapd_66_0F28,
    /*0f 29*/ &Processor::InstNotAvailable,
    /*0f 2a*/ &Processor::InstNotAvailable,
    /*0f 2b*/ &Processor::InstNotAvailable,
    /*0f 2c*/ &Processor::InstNotAvailable,
    /*0f 2d*/ &Processor::InstNotAvailable,
    /*0f 2e*/ &Processor::InstNotAvailable,
    /*0f 2f*/ &Processor::InstNotAvailable,
    /*0f 30*/ &Processor::InstNotAvailable,
    /*0f 31*/ &Processor::Rdtsc_0F31,
    /*0f 32*/ &Processor::InstNotAvailable,
    /*0f 33*/ &Processor::InstNotAvailable,
    /*0f 34*/ &Processor::InstNotAvailable,
    /*0f 35*/ &Processor::InstNotAvailable,
    /*0f 36*/ &Processor::InstNotAvailable,
    /*0f 37*/ &Processor::InstNotAvailable,
    /*0f 38*/ &Processor::InstNotAvailable,
    /*0f 39*/ &Processor::InstNotAvailable,
    /*0f 3a*/ &Processor::InstNotAvailable,
    /*0f 3b*/ &Processor::InstNotAvailable,
    /*0f 3c*/ &Processor::InstNotAvailable,
    /*0f 3d*/ &Processor::InstNotAvailable,
    /*0f 3e*/ &Processor::InstNotAvailable,
    /*0f 3f*/ &Processor::InstNotAvailable,
    /*0f 40*/ &Processor::Cmovo_0F40,
    /*0f 41*/ &Processor::Cmovno_0F41,
    /*0f 42*/ &Processor::Cmovb_0F42,
    /*0f 43*/ &Processor::Cmovnb_0F43,
    /*0f 44*/ &Processor::Cmove_0F44,
    /*0f 45*/ &Processor::Cmovne_0F45,
    /*0f 46*/ &Processor::Cmovbe_0F46,
    /*0f 47*/ &Processor::Cmova_0F47,
    /*0f 48*/ &Processor::Cmovs_0F48,
    /*0f 49*/ &Processor::Cmovns_0F49,
    /*0f 4a*/ &Processor::Cmovp_0F4A,
    /*0f 4b*/ &Processor::Cmovnp_0F4B,
    /*0f 4c*/ &Processor::Cmovl_0F4C,
    /*0f 4d*/ &Processor::Cmovge_0F4D,
    /*0f 4e*/ &Processor::Cmovle_0F4E,
    /*0f 4f*/ &Processor::Cmovg_0F4F,
    /*0f 50*/ &Processor::InstNotAvailable,
    /*0f 51*/ &Processor::InstNotAvailable,
    /*0f 52*/ &Processor::InstNotAvailable,
    /*0f 53*/ &Processor::InstNotAvailable,
    /*0f 54*/ &Processor::InstNotAvailable,
    /*0f 55*/ &Processor::InstNotAvailable,
    /*0f 56*/ &Processor::InstNotAvailable,
    /*0f 57*/ &Processor::Xorps_0F57,
    /*0f 58*/ &Processor::InstNotAvailable,
    /*0f 59*/ &Processor::InstNotAvailable,
    /*0f 5a*/ &Processor::InstNotAvailable,
    /*0f 5b*/ &Processor::InstNotAvailable,
    /*0f 5c*/ &Processor::InstNotAvailable,
    /*0f 5d*/ &Processor::InstNotAvailable,
    /*0f 5e*/ &Processor::InstNotAvailable,
    /*0f 5f*/ &Processor::InstNotAvailable,
    /*0f 60*/ &Processor::InstNotAvailable,
    /*0f 61*/ &Processor::InstNotAvailable,
    /*0f 62*/ &Processor::Punpckldq_0F62,
    /*0f 63*/ &Processor::InstNotAvailable,
    /*0f 64*/ &Processor::Pcmpgtb_0F64,
    /*0f 65*/ &Processor::InstNotAvailable,
    /*0f 66*/ &Processor::InstNotAvailable,
    /*0f 67*/ &Processor::InstNotAvailable,
    /*0f 68*/ &Processor::InstNotAvailable,
    /*0f 69*/ &Processor::InstNotAvailable,
    /*0f 6a*/ &Processor::InstNotAvailable,
    /*0f 6b*/ &Processor::InstNotAvailable,
    /*0f 6c*/ &Processor::InstNotAvailable,
    /*0f 6d*/ &Processor::InstNotAvailable,
    /*0f 6e*/ &Processor::Movd_0F6E,
    /*0f 6f*/ &Processor::Movdqa_0F6F,
    /*0f 70*/ &Processor::Pshufw_0F70,
    /*0f 71*/ &Processor::InstNotAvailable,
    /*0f 72*/ &Processor::Ext_0F72,
    /*0f 73*/ &Processor::InstNotAvailable,
    /*0f 74*/ &Processor::InstNotAvailable,
    /*0f 75*/ &Processor::InstNotAvailable,
    /*0f 76*/ &Processor::InstNotAvailable,
    /*0f 77*/ &Processor::Emms_0F77,
    /*0f 78*/ &Processor::InstNotAvailable,
    /*0f 79*/ &Processor::InstNotAvailable,
    /*0f 7a*/ &Processor::InstNotAvailable,
    /*0f 7b*/ &Processor::InstNotAvailable,
    /*0f 7c*/ &Processor::InstNotAvailable,
    /*0f 7d*/ &Processor::InstNotAvailable,
    /*0f 7e*/ &Processor::Movd_0F7E,
    /*0f 7f*/ &Processor::Movdqa_0F7F,
    /*0f 80*/ &Processor::Jo_0F80,
    /*0f 81*/ &Processor::Jno_0F81,
    /*0f 82*/ &Processor::Jc_0F82,
    /*0f 83*/ &Processor::Jnb_0F83,
    /*0f 84*/ &Processor::Jz_0F84,
    /*0f 85*/ &Processor::Jnz_0F85,
    /*0f 86*/ &Processor::Jna_0F86,
    /*0f 87*/ &Processor::Ja_0F87,
    /*0f 88*/ &Processor::Js_0F88,
    /*0f 89*/ &Processor::Jns_0F89,
    /*0f 8a*/ &Processor::Jp_0F8A,
    /*0f 8b*/ &Processor::Jpo_0F8B,
    /*0f 8c*/ &Processor::Jl_0F8C,
    /*0f 8d*/ &Processor::Jnl_0F8D,
    /*0f 8e*/ &Processor::Jng_0F8E,
    /*0f 8f*/ &Processor::Jnle_0F8F,
    /*0f 90*/ &Processor::Seto_0F90,
    /*0f 91*/ &Processor::Setno_0F91,
    /*0f 92*/ &Processor::Setc_0F92,
    /*0f 93*/ &Processor::Setnb_0F93,
    /*0f 94*/ &Processor::Setz_0F94,
    /*0f 95*/ &Processor::Setnz_0F95,
    /*0f 96*/ &Processor::Setna_0F96,
    /*0f 97*/ &Processor::Seta_0F97,
    /*0f 98*/ &Processor::Sets_0F98,
    /*0f 99*/ &Processor::Setns_0F99,
    /*0f 9a*/ &Processor::Setp_0F9A,
    /*0f 9b*/ &Processor::Setpo_0F9B,
    /*0f 9c*/ &Processor::Setl_0F9C,
    /*0f 9d*/ &Processor::Setnl_0F9D,
    /*0f 9e*/ &Processor::Setng_0F9E,
    /*0f 9f*/ &Processor::Setnle_0F9F,
    /*0f a0*/ &Processor::InstNotAvailable,
    /*0f a1*/ &Processor::InstNotAvailable,
    /*0f a2*/ &Processor::Cpuid_0FA2,
    /*0f a3*/ &Processor::Bt_0FA3,
    /*0f a4*/ &Processor::Shld_0FA4,
    /*0f a5*/ &Processor::Shld_0FA5,
    /*0f a6*/ &Processor::InstNotAvailable,
    /*0f a7*/ &Processor::InstNotAvailable,
    /*0f a8*/ &Processor::InstNotAvailable,
    /*0f a9*/ &Processor::InstNotAvailable,
    /*0f aa*/ &Processor::InstNotAvailable,
    /*0f ab*/ &Processor::InstNotAvailable,
    /*0f ac*/ &Processor::Shrd_0FAC,
    /*0f ad*/ &Processor::Shrd_0FAD,
    /*0f ae*/ &Processor::Ext_0FAE,
    /*0f af*/ &Processor::Imul_0FAF,
    /*0f b0*/ &Processor::InstNotAvailable,
    /*0f b1*/ &Processor::Cmpxchg_0FB1,
    /*0f b2*/ &Processor::InstNotAvailable,
    /*0f b3*/ &Processor::InstNotAvailable,
    /*0f b4*/ &Processor::InstNotAvailable,
    /*0f b5*/ &Processor::InstNotAvailable,
    /*0f b6*/ &Processor::Movzx_0FB6,
    /*0f b7*/ &Processor::Movzx_0FB7,
    /*0f b8*/ &Processor::InstNotAvailable,
    /*0f b9*/ &Processor::InstNotAvailable,
    /*0f ba*/ &Processor::Ext_0FBA,
    /*0f bb*/ &Processor::InstNotAvailable,
    /*0f bc*/ &Processor::InstNotAvailable,
    /*0f bd*/ &Processor::InstNotAvailable,
    /*0f be*/ &Processor::Movsx_0FBE,
    /*0f bf*/ &Processor::Movsx_0FBF,
    /*0f c0*/ &Processor::InstNotAvailable,
    /*0f c1*/ &Processor::Xadd_0FC1,
    /*0f c2*/ &Processor::InstNotAvailable,
    /*0f c3*/ &Processor::InstNotAvailable,
    /*0f c4*/ &Processor::InstNotAvailable,
    /*0f c5*/ &Processor::InstNotAvailable,
    /*0f c6*/ &Processor::InstNotAvailable,
    /*0f c7*/ &Processor::InstNotAvailable,
    /*0f c8*/ &Processor::Bswap_0FC8,
    /*0f c9*/ &Processor::Bswap_0FC8,
    /*0f ca*/ &Processor::Bswap_0FC8,
    /*0f cb*/ &Processor::Bswap_0FC8,
    /*0f cc*/ &Processor::Bswap_0FC8,
    /*0f cd*/ &Processor::Bswap_0FC8,
    /*0f ce*/ &Processor::Bswap_0FC8,
    /*0f cf*/ &Processor::Bswap_0FC8,
    /*0f d0*/ &Processor::InstNotAvailable,
    /*0f d1*/ &Processor::InstNotAvailable,
    /*0f d2*/ &Processor::InstNotAvailable,
    /*0f d3*/ &Processor::InstNotAvailable,
    /*0f d4*/ &Processor::InstNotAvailable,
    /*0f d5*/ &Processor::InstNotAvailable,
    /*0f d6*/ &Processor::Movq_0FD6,
    /*0f d7*/ &Processor::InstNotAvailable,
    /*0f d8*/ &Processor::InstNotAvailable,
    /*0f d9*/ &Processor::InstNotAvailable,
    /*0f da*/ &Processor::InstNotAvailable,
    /*0f db*/ &Processor::Pand_0FDB,
    /*0f dc*/ &Processor::InstNotAvailable,
    /*0f dd*/ &Processor::InstNotAvailable,
    /*0f de*/ &Processor::InstNotAvailable,
    /*0f df*/ &Processor::InstNotAvailable,
    /*0f e0*/ &Processor::InstNotAvailable,
    /*0f e1*/ &Processor::InstNotAvailable,
    /*0f e2*/ &Processor::InstNotAvailable,
    /*0f e3*/ &Processor::InstNotAvailable,
    /*0f e4*/ &Processor::InstNotAvailable,
    /*0f e5*/ &Processor::InstNotAvailable,
    /*0f e6*/ &Processor::InstNotAvailable,
    /*0f e7*/ &Processor::InstNotAvailable,
    /*0f e8*/ &Processor::InstNotAvailable,
    /*0f e9*/ &Processor::InstNotAvailable,
    /*0f ea*/ &Processor::InstNotAvailable,
    /*0f eb*/ &Processor::InstNotAvailable,
    /*0f ec*/ &Processor::InstNotAvailable,
    /*0f ed*/ &Processor::InstNotAvailable,
    /*0f ee*/ &Processor::InstNotAvailable,
    /*0f ef*/ &Processor::Pxor_0FEF,
    /*0f f0*/ &Processor::InstNotAvailable,
    /*0f f1*/ &Processor::InstNotAvailable,
    /*0f f2*/ &Processor::InstNotAvailable,
    /*0f f3*/ &Processor::InstNotAvailable,
    /*0f f4*/ &Processor::InstNotAvailable,
    /*0f f5*/ &Processor::InstNotAvailable,
    /*0f f6*/ &Processor::InstNotAvailable,
    /*0f f7*/ &Processor::InstNotAvailable,
    /*0f f8*/ &Processor::InstNotAvailable,
    /*0f f9*/ &Processor::InstNotAvailable,
    /*0f fa*/ &Processor::InstNotAvailable,
    /*0f fb*/ &Processor::InstNotAvailable,
    /*0f fc*/ &Processor::Paddb_0FFC,
    /*0f fd*/ &Processor::InstNotAvailable,
    /*0f fe*/ &Processor::InstNotAvailable,
    /*0f ff*/ &Processor::InstNotAvailable,
};

void Processor::InstNotAvailable(const Instruction *inst)
{
    LxFatal("Instruction unavailable: [%06x] %s\n", inst->Main.Inst.Opcode, inst->Main.CompleteInstr);
}

END_NAMESPACE_LOCHSEMU()